import type { Metadata } from "next";
import LogoX from "../../components/ui/LogoX";
import Navbar from "../../components/ui/Navbar";
import Button from "../../components/ui/Button";
import CardProfile from "../../components/ui/CardProfile";
import Search from "../../components/ui/Search";
import BoxBorder from "../../components/ui/BoxBorder";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-black`}>
        <main className="flex justify-between w-full">
          <section className="sticky 2xl:w-96 lg:w-80 border-right py-8 h-screen top-0 left-0 hidden lg:flex items-center lg:flex-col">
            <div className="flex flex-col justify-between h-screen">
              <div className="flex justify-start">
                <LogoX size={35} position={1} />
              </div>
              <Navbar />
              <div className="">
                <Button size={1}>Hello</Button>
              </div>
              <CardProfile
                imagem="/shelby.jpg"
                title="Imagem do usuário"
                descricao="gildo@gmail.com"
                size={1}
                nome="Gildo Henriques"
                estilo={1}
              />
            </div>
          </section>
          {children}
          <aside className="sticky space-y-5 h-screen p-5 2xl:w-96 lg:w-80 border-left top-0 right-0 hidden lg:flex lg:flex-col">
            <Search />
            <BoxBorder>
              <div className="flex justify-between mt-5 items-center">
                <CardProfile
                  imagem="/Vera.jpeg"
                  title="Imagem do usuário"
                  descricao="mara@gmail.com"
                  size={1}
                  nome="Vera Mota"
                  estilo={3}
                />
                <Button size={4}>
                  Seguir
                </Button>
              </div>
              <div className="flex justify-between mt-5 items-center">
                <CardProfile
                  imagem="/gildo.jpeg"
                  title="Imagem do usuário"
                  descricao="mara@gmail.com"
                  size={1}
                  nome="Gildo Cabeto"
                  estilo={3}
                />
                <Button size={4}>
                  Seguir
                </Button>
              </div>
              <div className="flex justify-between mt-5 items-center">
                <CardProfile
                  imagem="/Vera.jpeg"
                  title="Imagem do usuário"
                  descricao="mara@gmail.com"
                  size={1}
                  nome="Vera Mota"
                  estilo={3}
                />
                <Button size={4}>
                  Seguir
                </Button>
              </div>
            </BoxBorder>
          </aside>
        </main>
      </body>
    </html>
  );
}
